site:
  name: AeroX
  site: 'https://aeroxbefaster.com'
  base: '/'
  trailingSlash: true
  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

metadata:
  title:
    default: AeroX — Be Faster
    template: '%s — AeroX'
  description: "AeroX améliore ton aérodynamisme avec une simple webcam sur home trainer. Gagne 2–3 km/h à watts égaux en triathlon, Ironman ou course vélo. Mieux que Zwift, MyWhoosh, Kinomap."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AeroX
    images:
      - url: '~/assets/images/aerox-hero.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

# ⬇️ Conserve les 2 propriétés requises par le schéma…
i18n:
  language: fr            # requis par astrowind
  textDirection: ltr      # requis par astrowind

  # …et ajoute notre bloc multi-langues (propriétés additionnelles)
  defaultLocale: fr
  locales:
    - code: fr
      label: Français
      htmlLang: fr
      ogLocale: fr_FR
    - code: en
      label: English
      htmlLang: en
      ogLocale: en_GB

# Overrides de métadonnées par langue (optionnel mais utile)
metadata_i18n:
  fr:
    title:
      default: AeroX — Be Faster
      template: '%s — AeroX'
    description: "AeroX améliore ton aérodynamisme avec une simple webcam sur home trainer. Gagne 2–3 km/h à watts égaux…"
    openGraph:
      locale: fr_FR
  en:
    title:
      default: AeroX — Be Faster
      template: '%s — AeroX'
    description: "AeroX turns your smart trainer into a wind tunnel with a simple webcam. Gain 2–3 km/h…"
    openGraph:
      locale: en_GB

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark:only'
